  burger=document.querySelector('.burger')
  navbar=document.querySelector('.navbar')
  rightNav=document.querySelector('.rightNav')
  navlist=document.querySelector('.nav-list')
burger.addEventListener("click",()=>{
    rightNav.classList.toggle('v-nav-resp')
    navlist.classList.toggle('v-nav-resp')
    navbar.classList.toggle('h-nav-resp')
})
